spring:
  application:
    name: notification_service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console.enabled: true
  datasource:
    #    url: jdbc:h2:file:~/home/chris/dev/eucossa/notification_service/src/main/resources/data;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: create
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth:
          starttls:
            enable: true
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

